# Generated by Django 5.0.3 on 2024-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
