# Generated by Django 5.0.3 on 2024-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0003_alter_attempt_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='title'),
        ),
    ]
